export const SUPPORTED_COUNTRIES = {
  ug: {
    name: "Uganda",
    cities: [
      "Kampala",
      "Entebbe",
      "Jinja",
      "Mbarara",
      "Gulu",
      "Arua",
      "Mbale",
      "Soroti",
      "Lira",
      "Tororo",
      "Kabale",
      "Masaka",
      "Mukono",
      "Kasese",
      "Hoima",
      "Fort Portal",
      "Iganga",
      "Bushenyi",
      "Kisoro",
      "Kitgum",
    ],
    subLocations: {
      Kampala: [
        "Makindye",
        "Ntinda",
        "Kololo",
        "Nakasero",
        "Bukoto",
        "Muyenga",
        "Kabalagala",
        "Kiwatule",
        "Buziga",
        "Luzira",
        "Nsambya",
        "Kisugu",
        "Naguru",
        "Kampala Central",
        "Old Kampala",
        "Nakawa",
        "Kireka",
        "Bweyogerere",
        "Kyanja",
        "Kasangati",
        "Najjera",
        "Kisaasi",
      ],
      Nairobi: [
        "Westlands",
        "Kilimani",
        "Lavington",
        "Karen",
        "Muthaiga",
        "Upperhill",
        "Westlands",
        "Parklands",
        "Hurlingham",
        "Yaya",
        "South C",
        "South B",
        "Embakasi",
        "Donholm",
        "Buruburu",
        "Umoja",
        "Kasarani",
        "Ruiru",
        "Thika Road",
        "Mombasa Road",
      ],
      "Dar es Salaam": [
        "Oyster Bay",
        "Masaki",
        "Mbezi Beach",
        "Mikocheni",
        "Upanga",
        "City Centre",
        "Kinondoni",
        "Mwananyamala",
        "Sinza",
        "Msasani",
      ],
      Kigali: [
        "Kacyiru",
        "Kimihurura",
        "Remera",
        "Kiyovu",
        "Kigali Heights",
        "Kigali City Tower",
        "Kigali Convention Centre",
        "Kigali Heights",
        "Kigali City Tower",
        "Kigali Convention Centre",
        "Kacyiru",
        "Kimihurura",
        "Remera",
        "Kiyovu",
        "Kigali Heights",
        "Kigali City Tower",
        "Kigali Convention Centre",
      ],
    },
  },
  ke: {
    name: "Kenya",
    cities: [
      "Nairobi",
      "Mombasa",
      "Kisumu",
      "Nakuru",
      "Eldoret",
      "Thika",
      "Malindi",
      "Kakamega",
      "Nyeri",
      "Machakos",
      "Kericho",
      "Kisii",
      "Garissa",
      "Embu",
      "Bungoma",
      "Athi River",
      "Naivasha",
      "Kitale",
      "Kerugoya",
      "Voi",
    ],
    subLocations: {
      Nairobi: [
        "Westlands",
        "Kilimani",
        "Lavington",
        "Karen",
        "Muthaiga",
        "Upperhill",
        "Parklands",
        "Hurlingham",
        "Yaya",
        "South C",
        "South B",
        "Embakasi",
        "Donholm",
        "Buruburu",
        "Umoja",
        "Kasarani",
        "Ruiru",
        "Thika Road",
        "Mombasa Road",
        "Eastleigh",
        "Pangani",
        "Ngara",
      ],
      Mombasa: [
        "Nyali",
        "Bamburi",
        "Shanzu",
        "Mtwapa",
        "Diani Beach",
        "Ukunda",
        "Likoni",
        "Mombasa Island",
        "Old Town",
        "Bamburi",
        "Shanzu",
        "Mtwapa",
        "Nyali",
        "Bamburi",
        "Shanzu",
        "Mtwapa",
        "Diani Beach",
        "Ukunda",
        "Likoni",
        "Mombasa Island",
        "Old Town",
      ],
    },
  },
  tz: {
    name: "Tanzania",
    cities: [
      "Dar es Salaam",
      "Dodoma",
      "Mwanza",
      "Arusha",
      "Mbeya",
      "Morogoro",
      "Tanga",
      "Kigoma",
      "Musoma",
      "Iringa",
      "Songea",
      "Tabora",
      "Sumbawanga",
      "Bukoba",
      "Mtwara",
      "Lindi",
      "Singida",
      "Babati",
      "Korogwe",
      "Moshi",
    ],
    subLocations: {
      "Dar es Salaam": [
        "Oyster Bay",
        "Masaki",
        "Mbezi Beach",
        "Mikocheni",
        "Upanga",
        "City Centre",
        "Kinondoni",
        "Mwananyamala",
        "Sinza",
        "Msasani",
      ],
      Arusha: [
        "Arusha City Centre",
        "Njiro",
        "Sakina",
        "Themi",
        "Ngaramtoni",
        "Moshono",
      ],
      Dodoma: [
        "Dodoma City Centre",
        "Makutupora",
        "Chamwino",
        "Mpwapwa",
        "Kondoa",
      ],
    },
  },
  rw: {
    name: "Rwanda",
    cities: [
      "Kigali",
      "Butare",
      "Gitarama",
      "Ruhengeri",
      "Gisenyi",
      "Byumba",
      "Cyangugu",
      "Kibuye",
      "Kibungo",
      "Nyanza",
      "Ruhango",
      "Gikongoro",
      "Karongi",
      "Muhanga",
      "Musanze",
      "Huye",
      "Kayonza",
      "Rusizi",
      "Nyagatare",
    ],
    subLocations: {
      Kigali: [
        "Kacyiru",
        "Kimihurura",
        "Remera",
        "Kiyovu",
        "Kigali Heights",
        "Kigali City Tower",
        "Kigali Convention Centre",
      ],
    },
  },
  bi: {
    name: "Burundi",
    cities: [
      "Bujumbura",
      "Gitega",
      "Muyinga",
      "Ngozi",
      "Rutana",
      "Ruyigi",
      "Kayanza",
      "Bururi",
      "Makamba",
      "Muramvya",
      "Cibitoke",
      "Karuzi",
      "Kirundo",
      "Bubanza",
      "Cankuzo",
      "Isale",
      "Rumonge",
      "Gihanga",
      "Buhiga",
      "Kibuye",
    ],
    subLocations: {
      Bujumbura: [
        "Bujumbura Centre",
        "Kiriri",
        "Kigobe",
        "Musaga",
        "Bwiza",
        "Buyenzi",
        "Ngagara",
        "Kamenge",
        "Buterere",
        "Kinama",
      ],
    },
  },
  cd: {
    name: "DRC",
    cities: [
      "Kinshasa",
      "Lubumbashi",
      "Mbuji-Mayi",
      "Kananga",
      "Kisangani",
      "Bukavu",
      "Kolwezi",
      "Likasi",
      "Goma",
      "Kikwit",
      "Tshikapa",
      "Bunia",
      "Uvira",
      "Butembo",
      "Kindu",
      "Matadi",
      "Kalemie",
      "Kamina",
      "Mbandaka",
      "Kisantu",
    ],
    subLocations: {
      Kinshasa: [
        "Gombe",
        "Lingwala",
        "Ngaliema",
        "Masina",
        "Limete",
        "Kinshasa Central",
        "Bandalungwa",
        "Kintambo",
      ],
      Lubumbashi: [
        "Lubumbashi Centre",
        "Kampemba",
        "Katuba",
        "Annexe",
        "Kisanga",
      ],
    },
  },
};

export const getCountryByCode = (code) => {
  return SUPPORTED_COUNTRIES[code] || null;
};

export const getCountryCodeByName = (name) => {
  return Object.keys(SUPPORTED_COUNTRIES).find(
    (code) => SUPPORTED_COUNTRIES[code].name === name
  );
};

export const getCitiesByCountry = (countryCode) => {
  return SUPPORTED_COUNTRIES[countryCode]?.cities || [];
};

export const getSubLocationsByCity = (countryCode, cityName) => {
  return SUPPORTED_COUNTRIES[countryCode]?.subLocations?.[cityName] || [];
};

export const hasSubLocations = (countryCode, cityName) => {
  const subLocations = getSubLocationsByCity(countryCode, cityName);
  return subLocations.length > 0;
};

export const isValidCountryCode = (code) => {
  return Object.keys(SUPPORTED_COUNTRIES).includes(code);
};

export const getCurrencyByCountry = (countryCode) => {
  const currencies = {
    ug: "UGX",
    ke: "KES",
    tz: "TZS",
    rw: "RWF",
    bi: "BIF",
    cd: "CDF",
  };
  return currencies[countryCode] || "USD";
};
