export const SUPPORTED_COUNTRIES = {
  ug: {
    name: "Uganda",
    cities: [
      "Kampala",
      "Entebbe",
      "Jinja",
      "Mbarara",
      "Gulu",
      "Arua",
      "Mbale",
      "Soroti",
      "Lira",
      "Tororo",
      "Kabale",
      "Masaka",
      "Mukono",
      "Kasese",
      "Hoima",
      "Fort Portal",
      "Iganga",
      "Bushenyi",
      "Kisoro",
      "Kitgum",
    ],
  },
  ke: {
    name: "Kenya",
    cities: [
      "Nairobi",
      "Mombasa",
      "Kisumu",
      "Nakuru",
      "Eldoret",
      "Thika",
      "Malindi",
      "Kakamega",
      "Nyeri",
      "Machakos",
      "Kericho",
      "Kisii",
      "Garissa",
      "Embu",
      "Bungoma",
      "Athi River",
      "Naivasha",
      "Kitale",
      "Kerugoya",
      "Voi",
    ],
  },
  tz: {
    name: "Tanzania",
    cities: [
      "Dar es Salaam",
      "Dodoma",
      "Mwanza",
      "Arusha",
      "Mbeya",
      "Morogoro",
      "Tanga",
      "Kigoma",
      "Musoma",
      "Iringa",
      "Songea",
      "Tabora",
      "Sumbawanga",
      "Bukoba",
      "Mtwara",
      "Lindi",
      "Singida",
      "Babati",
      "Korogwe",
      "Moshi",
    ],
  },
  rw: {
    name: "Rwanda",
    cities: [
      "Kigali",
      "Butare",
      "Gitarama",
      "Ruhengeri",
      "Gisenyi",
      "Byumba",
      "Cyangugu",
      "Kibuye",
      "Kibungo",
      "Nyanza",
      "Ruhango",
      "Gikongoro",
      "Kibungo",
      "Karongi",
      "Muhanga",
      "Musanze",
      "Huye",
      "Kayonza",
      "Rusizi",
      "Nyagatare",
    ],
  },
  bi: {
    name: "Burundi",
    cities: [
      "Bujumbura",
      "Gitega",
      "Muyinga",
      "Ngozi",
      "Rutana",
      "Ruyigi",
      "Kayanza",
      "Bururi",
      "Makamba",
      "Muramvya",
      "Cibitoke",
      "Karuzi",
      "Kirundo",
      "Bubanza",
      "Cankuzo",
      "Isale",
      "Rumonge",
      "Gihanga",
      "Buhiga",
      "Kibuye",
    ],
  },
  cd: {
    name: "DRC",
    cities: [
      "Kinshasa",
      "Lubumbashi",
      "Mbuji-Mayi",
      "Kananga",
      "Kisangani",
      "Bukavu",
      "Kolwezi",
      "Likasi",
      "Goma",
      "Kikwit",
      "Tshikapa",
      "Bunia",
      "Uvira",
      "Butembo",
      "Kindu",
      "Matadi",
      "Kalemie",
      "Kamina",
      "Mbandaka",
      "Kisantu",
    ],
  },
};

export const getCountryByCode = (code) => {
  return SUPPORTED_COUNTRIES[code] || null;
};

export const getCountryCodeByName = (name) => {
  return Object.keys(SUPPORTED_COUNTRIES).find(
    (code) => SUPPORTED_COUNTRIES[code].name === name
  );
};

export const getCitiesByCountry = (countryCode) => {
  return SUPPORTED_COUNTRIES[countryCode]?.cities || [];
};

export const isValidCountryCode = (code) => {
  return Object.keys(SUPPORTED_COUNTRIES).includes(code);
};
